### ISSUE TITLE
Getting_Started-Slide: install.packages("GermaParl") doesn't seem to work

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/UCSSR#1]
> install.packages("drat")
drat::addRepo("polmine") # in diesem Fall: 'polmine' klein geschrieben
install.packages("cwbtools")
install.packages("GermaParl") # installation of package ‘GermaParl’ had non-zero exit status", weil die dependency polmineR.anno nicht da ist und den studis wohl auch nicht zur Verfügung stehen wird
library("cwbtools")
corpus_install("GermaParl") # Geändert: Das ist die alte Methode, die das Zeug vom sowi-server holt.

**Comment by PolMine** [comment]
The polmineR.anno-package has been moved to the 'Suggests' section of the DESCRIPTION file of the GermaParl package, so installation should work even if polmineR.anno is not yet publicly available. To be sure, I added the polmineR.anno package to the drat repository, so install.packages("GermaParl") will find polmineR.anno, and install it if necessary. It works on my system, and I feel confident to close the issue. Please let me know if the problem re-occurs!
