### ISSUE TITLE
KWIC-Slide: kwic(bt2005, query = "Ausländer", sAttribute = c("party", "date")) doesn't work

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/UCSSR#2]
Throws error:
kwic(bt2005,`` query = "Ausländer", sAttribute = c("party", "date"))
Fehler in .local(object, ...) : length(s_attribute) == 1 is not TRUE

Doesn't throw error but doesn't produce correct output:
kwic(bt2005,` query = "Ausländer", sAttributes = c("party", "date"))

Same behaviour with snake case.
 
Correct output:
kwic(bt2005, query = "Ausländer", meta = c("party", "date"))

**Comment by PolMine** [comment]
Cannot reproduce the error any more - has been solved with v0.7.10 of polmineR, which moved to argument s_attributes (not sAttributes), catching argument meta, if necessary.
